### ISSUE TITLE
视频点击崩溃

### ISSUE THREAD

**Issue by fightingfor** [chaychan/TouTiao#2]
java.lang.IllegalStateException
	at android.media.MediaPlayer.getCurrentPosition(Native Method)
	at com.chaychan.news.ui.activity.NewsDetailBaseActivity.postVideoEvent(NewsDetailBaseActivity.java:217)
	at com.chaychan.news.ui.activity.VideoDetailActivity.onBackPressed(VideoDetailActivity.java:110)
	at android.app.Activity.onKeyUp(Activity.java:2494)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2667)
	at android.app.Activity.dispatchKeyEvent(Activity.java:2751)
	at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:541)
	at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:319)
	at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2310)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4164)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4126)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3674)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3727)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3693)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3819)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3701)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3876)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3674)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3727)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3693)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3701)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3674)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3727)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3693)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3852)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4018)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2292)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1913)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1904)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2269)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:138)
	at android.app.ActivityThread.main(ActivityThread.java:5528)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:740)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630)

**Comment by chaychan** [comment]
@fightingfor 已经修复完毕，感谢你提出这个BUG
