### ISSUE TITLE
.Activity.getWindow()' on a null object reference问题

### ISSUE THREAD

**Issue by 673295195** [chaychan/TouTiao#26]
在fragment里面播放视频,不知道为什么jcvideoplayer_lib\JCVideoPlayer.java这个类的341行报.Activity.getWindow()' on a null object reference空指针.注掉就没问题  .activity没这个问题

**Comment by 673295195** [comment]
但是如果是多视频,点击一个没问题,但是点击第2个就还是不行

**Comment by 673295195** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.app.Activity.getWindow()' on a null object reference
        at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onCompletion(JCVideoPlayer.java:525)
        at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onCompletion(JCVideoPlayerStandard.java:781)
        at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerManager.completeAll(JCVideoPlayerManager.java:42)
        at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.startVideo(JCVideoPlayer.java:335)
        at com.sz.mgcoin.gameplatform.adapter.VideoAdapter$VideoHolder$1.onVideoClickToStart(VideoAdapter.java:80)
        at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(JCVideoPlayer.java:170)
        at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onClick(JCVideoPlayerStandard.java:190)
        at android.view.View.performClick(View.java:5205)
        at android.view.View$PerformClick.run(View.java:21175)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5435)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
