### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by xiexikui** [chaychan/TouTiao#3]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.chaychan.news, PID: 1979
                                                 java.lang.RuntimeException: Unable to instantiate application com.chaychan.news.app.MyApp: java.lang.ClassNotFoundException: Didn't find class "com.chaychan.news.app.MyApp" on path: DexPathList[[zip file "/data/app/com.chaychan.news-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.chaychan.news-1, /system/lib]]
                                                     at android.app.LoadedApk.makeApplication(LoadedApk.java:516)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4319)
                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5019)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.chaychan.news.app.MyApp" on path: DexPathList[[zip file "/data/app/com.chaychan.news-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.chaychan.news-1, /system/lib]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:992)
                                                     at android.app.LoadedApk.makeApplication(LoadedApk.java:511)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4319) 
                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5019) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515)

**Comment by chaychan** [comment]
@xiexikui 这崩溃问题严重，是安装后打不开吧

**Comment by xiexikui** [comment]
是的，夜神模拟器安装点击就崩溃，我正在看是什么原因

**Comment by xiexikui** [comment]
@chaychan 重新编译以后又好了，用你的apk就会出现这个问题

**Comment by chaychan** [comment]
@xiexikui 嗯嗯
