### ISSUE TITLE
打开就崩溃 - -

### ISSUE THREAD

**Issue by af199901** [chaychan/TouTiao#4]
7-31 15:28:41.671 25490-25490/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.chaychan.news, PID: 25490
                                                   java.lang.RuntimeException: Unable to instantiate application com.chaychan.news.app.MyApp: java.lang.ClassNotFoundException: Didn't find class "com.chaychan.news.app.MyApp" on path: DexPathList[[zip file "/data/app/com.chaychan.news-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.chaychan.news-1, /vendor/lib, /system/lib]]
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:519)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4416)
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:143)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1269)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5120)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.chaychan.news.app.MyApp" on path: DexPathList[[zip file "/data/app/com.chaychan.news-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.chaychan.news-1, /vendor/lib, /system/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:975)
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:514)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4416) 
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:143) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1269) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5120) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634) 
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by chaychan** [comment]
@312353457 您是不是也是用夜神模拟器出现的问题

**Comment by af199901** [comment]
不是  oppo a31  4.4的系统

**Comment by chaychan** [comment]
@312353457 奇怪，我得查查看为什么出这问题

**Comment by chaychan** [comment]
@312353457 我也试了4.1.1的模拟器，也出现崩溃的问题，重写clean项目编译后，运行没有问题了，估计是上次生成的apk包有问题，现在已经更新了安装包，多谢你提出的问题

**Comment by af199901** [comment]
博主太客气。 我测出了两个问题，第一次点击视频tab，整个界面会向上移动一段，就是整个tab栏下面会多一个10dp左右的空白，触发的条件是我进来第一次必须先点视频，点其他再点视频就不会有这样的情况。然后视频播不了，好像jc问题有点多，我自己用的时候改到放弃。

**Comment by chaychan** [comment]
@312353457 JC的确问题多多，不过目前也没有其他更好的视频播放框架，或者还没了解到。

**Comment by 983045775** [comment]
怎么不考虑用ijk

**Comment by chaychan** [comment]
@983045775 IJKPlayer么，到时试试看
